django-blog/accounts/urls.py
from django.urls import path
from .views import Registration, Login, Logout, Update, PasswordChange


app_name = 'accounts'

urlpatterns = [
    path('join/', Registration, name='register'),
    path('login/', Login, name='login'),
    path('logout/', Logout, name='logout'),
    path('update/', Update, name='update'),
    path('update/pw-change', PasswordChange, name='pw-change'),
]

django-blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

from django.conf.urls.static import static
from django.conf import settings


app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('blog/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
# img
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-blog/posts/urls.py
from django.urls import path
from .views import PostView, PostDetail, PostWrite, PostEdit, PostDelete, PostSerach, CommentWrite, CommentDelete, ReCommentWrite, ReCommentDelete


app_name = 'blog'

urlpatterns = [
    path('', PostView, name='list'),
    path('<int:post_id>/', PostDetail, name='detail'),
    path('write/', PostWrite, name='write'),
    path('<int:post_id>/edit/', PostEdit, name='edit'),
    path('<int:post_id>/delete/', PostDelete, name='delete'),
    path('search/', PostSerach, name='search'),
    path('<int:post_id>/comment/write/', CommentWrite, name='cm-write'),
    path('<int:post_id>/comment/<int:pk>/delete/', CommentDelete, name='cm-delete'),
    path('<int:post_id>/comment/<int:comment_id>/recomment/write/', ReCommentWrite, name='recomment-write'),
    path('<int:post_id>/ReComment/<int:pk>/delete', ReCommentDelete, name='recomment-delete'),
]

django-blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko-KR">
	<head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
            {{title}}
        </title>
        <!-- reset.css : meyerweb -->
        <link rel="stylesheet" href="{% static '/css/reset.css' %}" />
        <!-- font : pretendard -->
        <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
        <link rel="stylesheet" href="{% static '/css/global.css' %}" />
        <!-- layout -->
        <link rel="stylesheet" href="{% static '/css/header.css' %}" />
        <link rel="stylesheet" href="{% static '/css/footer.css' %}" />
        <!-- component -->
        <link rel="stylesheet" href="{% static '/css/button.css' %}" />
        <link rel="stylesheet" href="{% static '/css/banner.css' %}" />
        <link rel="stylesheet" href="{% static '/css/category.css' %}" />
        <link rel="stylesheet" href="{% static '/css/author.css' %}" />
	</head>
	<body>
		<!-- header -->
		<header>
			<div class="max-width">
				<h1>
					<a href="/">
						<img src="{% static './assets/Logo.svg' %}" alt="My Blog" />
					</a>
				</h1>
				<ul>
					{% if user.is_active %}
					<li class="profile-img">
						<a href="{% url 'accounts:update' %}">
							<img src="{% static './assets/profile.jpg' %}" alt="My Page" />
						</a>
					</li>
					<li>
						<a class="button white" href="{% url 'accounts:logout' %}">
							<img src="{% static './assets/icon-logout.svg' %}" alt="" />
							<span>Logout</span>
						</a>
					</li>
					{% else %}
					<li>
						<a href="{% url 'accounts:login' %}" class="button">
							<span>Login</span>
						</a>
					</li>
					<li>
						<a href="{% url 'accounts:register' %}" class="button">
							<span>Register</span>
						</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</header>
		<!--// header -->

		<!-- banner -->
		<div class="banner">
			<div class="max-width">
				<div class="banner-contents">
					<p class="sub-text">React Blog</p>
					<p class="main-text">My BLOG</p>
					<p class="description">
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis nostrum dolor provident beatae deserunt magnam, illo neque. Maiores ipsum commodi dolorum beatae aliquid laboriosam est
					</p>
				</div>
			</div>
		</div>
		<!-- //banner -->

		<!-- main -->
		{% block content %}
        {% endblock %}
		<!-- //main -->
		
        <!-- footer -->
		<footer>
			<div class="max-width">
				<h2>©Weniv Corp.</h2>
				<button class="top-button">TOP</button>
			</div>
		</footer>
		<!-- //footer -->
	</body>
</html>

django-blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'blog:list' %}" class="button">
    <span>블로그 입장하기</span>
</a>
{% endblock %}