django-blog/accounts/urls.py
from django.urls import path
from .views import Registration, Login, Logout, Update, PasswordChange


app_name = 'accounts'

urlpatterns = [
    path('join/', Registration, name='register'),
    path('login/', Login, name='login'),
    path('logout/', Logout, name='logout'),
    path('update/', Update, name='update'),
    path('update/pw-change', PasswordChange, name='pw-change'),
]

django-blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

from django.conf.urls.static import static
from django.conf import settings


app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('blog/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
# img
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-blog/posts/urls.py
from django.urls import path
from .views import PostView, PostDetail, PostWrite, PostEdit, PostDelete, PostSerach, CommentWrite, CommentDelete, ReCommentWrite, ReCommentDelete


app_name = 'blog'

urlpatterns = [
    path('', PostView, name='list'),
    path('<int:post_id>/', PostDetail, name='detail'),
    path('write/', PostWrite, name='write'),
    path('<int:post_id>/edit/', PostEdit, name='edit'),
    path('<int:post_id>/delete/', PostDelete, name='delete'),
    path('search/', PostSerach, name='search'),
    path('<int:post_id>/comment/write/', CommentWrite, name='cm-write'),
    path('<int:post_id>/comment/<int:pk>/delete/', CommentDelete, name='cm-delete'),
    path('<int:post_id>/comment/<int:comment_id>/recomment/write/', ReCommentWrite, name='recomment-write'),
    path('<int:post_id>/ReComment/<int:pk>/delete', ReCommentDelete, name='recomment-delete'),
]

django-blog/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(unique=True, max_length=20)
    email = models.CharField(max_length=255, null=True, blank=True)
    nickname = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.TimeField(auto_now_add=True)
    updated_at = models.TimeField(auto_now=True)

django-blog/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms


User = get_user_model()


class RegisterForm(UserCreationForm):
    username = forms.CharField(label="아이디")
    
    class Meta:
        model = User
        fields = ['username']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="아이디")

    error_messages = {
        'invalid_login': (
            f"올바른 아이디와 비밀번호를 입력하십시오. 두 필드 모두 대문자와 소문자를 구별합니다."
        ),
        'inactive': ("This account is inactive."),
    }
    
    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=100, disabled=True, label="아이디")
    nickname = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(max_length=255, required=False)

    class Meta:
        model = User
        fields = ['username', 'nickname', 'email']

    def save(self, commit=True):
        user = super().save(commit=False)
        
        user.nickname = self.cleaned_data.get('nickname')
        user.email = self.cleaned_data.get('email')
        
        if commit:
            user.save()
        
        return user


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

django-blog/accounts/views.py
from typing import Any, Dict
from django.views.generic.edit import FormView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm, ProfileForm, CustomPasswordChangeForm


class Registration(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('blog:list')
        return super().get(request, *args, **kwargs)

### Login
class Login(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            form.add_error(None, 'Invalid username or password')
            return super().form_invalid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('blog:list')
        return super().get(request, *args, **kwargs)


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('blog:list')


class Update(LoginRequiredMixin, FormView):
    template_name = 'accounts/update.html'
    form_class = ProfileForm
    success_url = reverse_lazy('blog:list')

    def get_initial(self):
        initial = super().get_initial()
        initial['username'] = self.request.user.username
        initial['nickname'] = self.request.user.nickname
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, self.request.user)
        return super().form_valid(form)


class PasswordChange(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('blog:list')
    template_name = 'accounts/change_password.html'


Registration = Registration.as_view()
Login = Login.as_view()
Logout = Logout.as_view()
Update = Update.as_view()
PasswordChange = PasswordChange.as_view()

django-blog/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login-join.css' %}">
</head>
<div class="main">
    <div class="container">
        <h2 class="title">Change Password</h2>
        <p class="description">
            Here you can change your password.
        </p>

        <form class="password_change" method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="submit-button" type="submit">Change password</button>
            <a href="{% url 'blog:list' %}" class="button">Back</a>
        </form>
    </div>
</div>
{% endblock %}

django-blog/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login-join.css' %}">
</head>
<div class="main">
    <div class="container">
        <h2 class="title">로그인</h2>
        <p class="description">아이디와 비밀번호를 입력하고 로그인하세요</p>

        <form class="login" method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">                                                           
                <label for="{{field.id_for_label }}">{{field.label}}:</label>
                <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label }}"
                            placeholder="{{field.label}}" name="{{field.name}}"/>
            </div>
            {% if field.errors %}
            <span style="color: red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button class="submit-button" type="submit">로그인</button>
            <ui>
                <li>
                    <a href="{% url 'blog:list' %}">
                        <span>돌아가기</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:register' %}" class="button">
                        <span>Register</span>
                    </a>
                </li>
            </ui>
        </form>
    </div>
</div>
{% endblock %}

django-blog/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login-join.css' %}">
</head>
<div class="main">
    <div class="container">
        <h2 class="title">회원가입</h2>
        <p class="description">
            원활한 서비스를 이용을 위해 회원가입을 해주세요
        </p>

        <form class="register" method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            </div>
            <button class="submit-button" type="submit">회원가입</button>
            <a href="{% url 'blog:list' %}">돌아가기</a>
        </form>
    </div>
</div>
{% endblock %}

django-blog/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login-join.css' %}">
</head>
<div class="main">
    <div class="container">
        <h2 class="title">회원정보</h2>
        <p class="description">
            회원정보 변경이 가능합니다.
        </p>

        <form class="update" method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'accounts:pw-change' %}" class="button">비밀번호 변경</a>
            <button class="submit-button" type="submit">정보 변경</button>
            <a href="{% url 'blog:list' %}" class="button">돌아가기</a>
        </form>
    </div>
</div>
{% endblock %}