django-blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

from django.conf.urls.static import static
from django.conf import settings


app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('blog/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
# img
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-blog/posts/urls.py
from django.urls import path
from .views import PostView, PostDetail, PostWrite, PostEdit, PostDelete, PostSerach, CommentWrite, CommentDelete, ReCommentWrite, ReCommentDelete


app_name = 'blog'

urlpatterns = [
    path('', PostView, name='list'),
    path('<int:post_id>/', PostDetail, name='detail'),
    path('write/', PostWrite, name='write'),
    path('<int:post_id>/edit/', PostEdit, name='edit'),
    path('<int:post_id>/delete/', PostDelete, name='delete'),
    path('search/', PostSerach, name='search'),
    path('<int:post_id>/comment/write/', CommentWrite, name='cm-write'),
    path('<int:post_id>/comment/<int:pk>/delete/', CommentDelete, name='cm-delete'),
    path('<int:post_id>/comment/<int:comment_id>/recomment/write/', ReCommentWrite, name='recomment-write'),
    path('<int:post_id>/ReComment/<int:pk>/delete', ReCommentDelete, name='recomment-delete'),
]

django-blog/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)  # user foreignkey
    category_choices = (('일반', '일반'), ('공지사항', '공지사항'))
    category = models.CharField(max_length=20, choices=category_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 조회수
    hit = models.PositiveIntegerField(default=0)
    # 이미지
    img = models.ImageField(upload_to="", blank=True, null=True)

    def __str__(self):
        return self.title

    def update_counter(self):
        self.hit = self.hit + 1
        self.save()


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class ReComment(models.Model):
    parent = models.ForeignKey(Comment, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

django-blog/posts/forms.py
from django import forms
from .models import Post, Comment, ReComment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'img']


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']


class ReCommentForm(forms.ModelForm):

    class Meta:
        model = ReComment
        fields = ['content']

django-blog/posts/views.py
from typing import Any
from django.http import Http404, HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment, ReComment
from .forms import PostForm, CommentForm, ReCommentForm

# Create your views here.
class PostView(ListView):
    model = Post
    template_name = 'posts/list.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog'
        context['search'] = ''
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'posts/detail.html'
    context_object_name = 'post'

    def get_object(self):
        try:
            object = get_object_or_404(Post, id=self.kwargs['post_id'])
            object.update_counter()
            return object
        except Http404:
            return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        context['post'] = get_object_or_404(Post, pk=post_id)
        context['comments'] = Comment.objects.filter(post_id=post_id)
        context['comment_form'] = CommentForm()
        context['recomment_form'] = ReCommentForm()
        return context


class PostWrite(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = Post
    fields = ['title', 'content', 'category', 'img']
    template_name = 'posts/write.html'
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.save()
        return super().form_valid(form)


class PostEdit(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = Post
    fields = ['title', 'content', 'category', 'img']
    template_name = 'posts/edit.html'
    context_object_name = 'post'
    success_url = reverse_lazy('blog:list')

    def get_object(self):

        object = get_object_or_404(Post, id=self.kwargs['post_id'])
        return object
    
    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.save()
        return super().form_valid(form)


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')

    def get_object(self):

        object = get_object_or_404(Post, id=self.kwargs['post_id'])
        return object

# ?뒤에 커리문 처리 예정
class PostSerach(ListView):
    model = Post
    template_name = 'posts/list.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        queryset = Post.objects.all()

        tag = self.request.GET.get('tag', '')
        category = self.request.GET.get('category', '')

        if tag:
            queryset = queryset.filter(title__contains=tag) | queryset.filter(content__contains=tag)
        if category:
            queryset = queryset.filter(category=category)
        
        sort_order = self.request.GET.get('sort', 'newest')
        if sort_order == 'newest':
            queryset = queryset.order_by('-created_at')
        else:
            queryset = queryset.order_by('created_at')

        print(list(queryset))
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog'
        return context
    

class CommentWrite(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'posts/detail.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.instance.post = Post.objects.get(pk=self.kwargs['post_id'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:detail', kwargs={'post_id': self.object.post.pk})


class CommentDelete(DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'post_id': self.object.post.id})


class ReCommentWrite(LoginRequiredMixin, CreateView):
    model = ReComment
    form_class = ReCommentForm
    template_name = 'posts/detail.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.instance.parent = get_object_or_404(Comment, pk=self.kwargs['comment_id'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:detail', kwargs={'post_id': self.object.parent.post.pk})


class ReCommentDelete(DeleteView):
    model = ReComment

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'post_id': self.object.parent.post.id})


PostView = PostView.as_view()
PostDetail = PostDetail.as_view()
PostWrite = PostWrite.as_view()
PostEdit = PostEdit.as_view()
PostDelete = PostDelete.as_view()
PostSerach = PostSerach.as_view()
CommentWrite = CommentWrite.as_view()
CommentDelete = CommentDelete.as_view()
ReCommentWrite = ReCommentWrite.as_view()
ReCommentDelete = ReCommentDelete.as_view()

django-blog/posts/templates/posts/detail.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
</head>
    <h1>제목: {{ post.title }}</h1>
    <p>내용: {{ post.content }}</p>
    {% if post.img %}
    <img src="{{ post.img.url }}" alt="image" width="700">
    {% endif %}
    <p>
        작성자: 
        {% if post.writer.nickname %}
            {{ post.writer.nickname }}
        {% else %}
            {{ post.writer }}
        {% endif %}
    </p>
    <p>작성일: {{ post.created_at }}</p>
    <p>조회수: {{ post.hit }}</p>
    <hr>
    {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' post.id %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' post.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}
    <h3>댓글</h3>
    {% for comment in comments %}
        <div>
            <p><strong>{{ comment.writer.username }}:</strong> {{ comment.content }}</p>
	    {% if comment.writer == request.user %}
            <form action="{% url 'blog:cm-delete' post_id=post.id pk=comment.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="삭제" class="btn">
            </form>
	    {% endif %}

            <h4>대댓글</h4>
            {% for recomment in comment.recomment_set.all %}
                <div>
                    <p><strong>{{ recomment.writer.username }}:</strong> {{ recomment.content }}</p>
		    {% if recomment.writer == request.user %}
		    <form action="{% url 'blog:recomment-delete' post_id=post.id pk=recomment.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="삭제" class="btn">
		    </form>
		    {% endif %}
                </div>
            {% endfor %}

            <h5>대댓글 작성</h5>
            <form action="{% url 'blog:recomment-write' post_id=post.id comment_id=comment.id %}" method="post">
                {% csrf_token %}
                {{ recomment_form.as_p }}
                <input type="submit" value="{% trans 'Submit' %}">
            </form>
        </div>
    {% endfor %}

    <h3>댓글 작성</h3>
    <form id="comment-form" action="{% url 'blog:cm-write' post_id=post.id %}" method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="{% trans 'Submit' %}">
    </form>

    <br>
    <a href="{% url 'blog:list' %}" class="button">돌아가기</a>
{% endblock %}

django-blog/posts/templates/posts/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/write.css' %}">
</head>
<form action="{% url 'blog:edit' post.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
</form>
<a href="{% url 'blog:list' %}">돌아가기</a>
{% endblock %}

django-blog/posts/templates/posts/list.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/list.view.css' %}">

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.view' %}">
</head>
<div class="main">
    <h2 class="main-title">
        {{ title }}
    </h2>

    <div>
        <form class="search-form" method="get" action="{% url 'blog:search' %}">
            <label for="category" class="a11y-hidden">카테고리</label>
            <select id="category" name="category">
                <option value="">전체</option>
                <option value="공지사항">공지사항</option>
                <option value="일반">일반</option>
            </select>
            <label for="tag" class="a11y-hidden">Search</label>
            <input id="tag" type="search" name="tag" placeholder="제목 + 내용 검색">
            <label for="sort" class="a11y-hidden">정렬</label>
            <select id="sort" name="sort">
                <option value="oldest">날짜 오름차순</option>
                <option value="newest">날짜 내림차순</option>
            </select>
            <button type="submit">검색</button>
        </form>
    </div>

    <!-- 게시판 리스트 -->
    <table class="table table-bordered">
        <colgroup>
            <col style="width: 10%">
            <col style="width: 10%">
            <col style="width: 20%">
            <col style="width: 20%">
            <col style="width: 10%">
            <col style="width: 10%">
        </colgroup>
        <thead class="table-light">
            <tr>
                <th>카테고리</th>
                <th>조회수</th>
                <th>제목</th>
                <th>내용</th>
                <th>작성자</th>
                <th>일자</th>
            </tr>
        </thead>
        <tbody>
        {% if posts %}
        {% for post in posts %}
            <tr>
                <td>{{ post.category }}</td>
                <td>{{ post.hit }}</td>
                <td><a href="{% url 'blog:detail' post_id=post.pk %}" class="btn">{{ post.title }} [{{ post.comment_set.count }}]</a></td>
                <td>{{ post.content }}</td>
                <td>
                    {% if post.writer.nickname %}
                        {{ post.writer.nickname }}
                    {% else %}
                        {{ post.writer }}
                    {% endif %}
                </td>
                <td>{{ post.created_at }}</td>
            </tr>
        {% endfor %}
        </tbody>
        {% else %}
            <p>작성된 게시물이 없습니다.</p>
        {% endif %}
    </table>
    <div class="btn-group">
        {% if user.is_active %}
        <a href="{% url 'blog:write' %}" class="button">
            <img src="{% static './assets/icon-modify-white.svg' %}" alt="" />
            <span>글쓰기</span>
        </a>
        {% endif %}
    </div>
</div>
{% endblock %}

django-blog/posts/templates/posts/not_found.html
{% extends 'base.html' %}

{% block content %}
<h1><존재하지 않는 게시글입니다></h1>
<a href="{% url 'blog:list' %}">돌아가기</a>
{% endblock %}

django-blog/posts/templates/posts/write.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/write.css' %}">
</head>
<div class="main">
    <!-- 글쓰기 페이지 -->
    <h2 class="main-title">글쓰기</h2>
    <p class="main-desc">내용을 입력 해주세요.</p>

    <form action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table write">
            <colgroup>
                <col style="width: 120px">
                <col>
            </colgroup>
                {{ form.as_p }}
        <input type="submit" class="btn btn btn-success">
        <a href="{% url 'blog:list' %}">돌아가기</a>
    </form>

        <!--  //글쓰기 페이지 -->
    </div>
{% endblock %}